# Generated by Django 5.2 on 2025-05-11 00:09

import etc.helper_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=etc.helper_functions.profile_image_uploader),
        ),
    ]
