# Generated by Django 5.2 on 2025-06-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
