# Generated by Django 5.2 on 2025-08-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhub', '0002_alter_invoice_shipping_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='shipping_address_id',
            new_name='shipping_address',
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orderhub.invoice'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_method_info',
            field=models.CharField(choices=[('CASH', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('BANK', 'Bank Transfer'), ('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('APPLE', 'Apple Pay'), ('GOOGLE', 'Google Pay'), ('VODAFONE', 'Vodafone Cash'), ('FAWRY', 'Fawry'), ('AMAN', 'Aman'), ('MEEZA', 'Meeza Card'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled by user or system'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('CHARGEBACK', 'Chargeback Requested'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('DECLINED', 'Declined by provider'), ('WAITING_3DS', 'Waiting 3DS Authentication')], default='PENDING', max_length=20),
        ),
    ]
