# Generated by Django 5.2 on 2025-05-11 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(choices=[('#FF0000', 'Red'), ('#00FF00', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#800080', 'Purple'), ('#FFC0CB', 'Pink'), ('#A52A2A', 'Brown'), ('#808080', 'Gray'), ('#000000', 'Black'), ('#FFFFFF', 'White'), ('#00FFFF', 'Cyan'), ('#008080', 'Teal'), ('#FFD700', 'Gold'), ('#4B0082', 'Indigo'), ('#F5F5DC', 'Beige'), ('#D2691E', 'Chocolate')], default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Black', 'Black'), ('White', 'White'), ('Cyan', 'Cyan'), ('Teal', 'Teal'), ('Gold', 'Gold'), ('Indigo', 'Indigo'), ('Beige', 'Beige'), ('Chocolate', 'Chocolate')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large'), ('OVER', 'Oversize'), ('ONE_SIZE', 'One Size Fits All'), ('GEN', 'General Size')], default=1, max_length=9, unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='productcolor',
            constraint=models.UniqueConstraint(fields=('product', 'color'), name='unique_product_color'),
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size'),
        ),
    ]
