# Generated by Django 5.2 on 2025-05-11 01:32

import django.db.models.deletion
import django.utils.timezone
import etc.helper_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_color_color_code_color_name_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='alt_text',
            field=models.CharField(default='add alt text', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmedia',
            name='file_url',
            field=models.FileField(upload_to=etc.helper_functions.product_media_uploader),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmedia',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
