# Generated by Django 5.2 on 2025-05-11 18:27

import django.db.models.deletion
import etc.helper_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_created_at_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=10)),
                ('file_url', models.FileField(upload_to=etc.helper_functions.category_media_uploader)),
                ('alt_text', models.CharField(max_length=100)),
                ('is_main', models.BooleanField(default=False, help_text='cover image in case of true')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
