# Generated by Django 5.2 on 2025-07-06 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sale_discount_percent_sale_end_date_sale_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='only_one_active_sale_per_product',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='unique_main_image_per_product'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product',), name='only_one_active_sale_per_product'),
        ),
    ]
