# Generated by Django 5.2 on 2025-05-12 02:17

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sale_discount_percent_sale_end_date_sale_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='only_one_active_sale_per_product',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__gte', datetime.datetime(2025, 5, 12, 2, 17, 12, 418420, tzinfo=datetime.timezone.utc))), fields=('product',), name='only_one_active_sale_per_product'),
        ),
    ]
