# Generated by Django 5.2 on 2025-07-06 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_sale_only_one_active_sale_per_product_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__gte', datetime.datetime(2025, 7, 6, 18, 24, 22, 523225, tzinfo=datetime.timezone.utc))), fields=('product', 'is_active'), name='only_one_active_sale_per_product'),
        ),
    ]
