# Generated by Django 5.2 on 2025-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_sale_only_one_active_sale_per_product_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categorymedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('category',), name='unique_main_image_per_category'),
        ),
    ]
